### ISSUE TITLE
"too many terminals, data makes no sense" while store data to node

### ISSUE THREAD

**Issue by abuvanth** [cyberfly-io/cyberfly-node#17]
file:///Users/abu/cyberfly-node/node_modules/cborg/lib/decode.js:204
    throw new Error(`${decodeErrPrefix} too many terminals, data makes no sense`)
          ^

Error: CBOR decode error: too many terminals, data makes no sense
    at Module.decode (file:///Users/abu/cyberfly-node/node_modules/cborg/lib/decode.js:204:11)
    at Module.decode (file:///Users/abu/cyberfly-node/node_modules/@ipld/dag-cbor/src/index.js:147:39)
    at Module.decode (file:///Users/abu/cyberfly-node/node_modules/@orbitdb/core/node_modules/multiformats/src/block.js:207:23)
    at Object.decode (file:///Users/abu/cyberfly-node/node_modules/@orbitdb/core/src/oplog/entry.js:150:33)
    at task (file:///Users/abu/cyberfly-node/node_modules/@orbitdb/core/src/database.js:143:33)
    at file:///Users/abu/cyberfly-node/node_modules/p-queue/dist/index.js:180:37
    at #tryToStartAnother (file:///Users/abu/cyberfly-node/node_modules/p-queue/dist/index.js:118:17)
    at file:///Users/abu/cyberfly-node/node_modules/p-queue/dist/index.js:204:36
    at new Promise (<anonymous>)
    at PQueue.add (file:///Users/abu/cyberfly-node/node_modules/p-queue/dist/index.js:174:16)
Emitted 'error' event at:
    at task (file:///Users/abu/cyberfly-node/node_modules/@orbitdb/core/src/sync.js:224:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/abu/cyberfly-node/node_modules/p-queue/dist/index.js:187:36

Node.js v22.0.0

**Comment by abuvanth** [comment]
https://github.com/cyberfly-io/cyberfly-node/commit/193d8ff99af37919f9fab507f0085af23df531d7
